notifications:
  email: off

env:
  global:
    TERM=dumb

language: java
jdk: openjdk8

addons:
  apt:
    packages:
      - httpie

install: true

script:
  - ./gradlew build
  - bash ./build/libs/*.jar &
  - sleep 15

  # ratpack REST API:
  - http :5050
  - http :5050/Max
  - http :5050/skip/x
  - http :5050/skip/f/b

  # mongo hateoas repo:
  - http :8080
  - http :8080/users
  
cache:
  directories:
    - /usr/local/lib/
    - ~/.gradle/
    - ~/.cache/
    - ~/.nvm/
    - ~/.m2/
